# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: '#about'
    weight: 10
  - name: Research Interests
    url: '#featured'
    weight: 20
  - name: Lab Experiences
    url: '#featured'
    weight: 30
  - name: Class Projects
    url: '#projects'
    weight: 40
  - name: CV
    url: uploads/Academic_CV.pdf
    weight: 50
  - name: Hobbies
    url: '#slides'
    weight: 60
  # - name: Current Status
  #   url: '#featured'
  #   weight: 70

